version : '2'
services:

  coverage_collector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    container_name: coverage_collector_container

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cc
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    container_name: mysql_container
